version: '3.8'

services:
  resume-web:
    image: alikaan-me:latest
    container_name: alikaan-me-web
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - alikaan-me-network

networks:
  alikaan-me-network:
    driver: bridge
